"""EN: the example notebook ships with the package and runs from a plain `pip install`: the data come from inside the
package (no download, no path to fix), and `examples --copy` hands it over together with the CSV. ONE notebook, with
the narration in the four languages of the tool in every text cell (user decision, 2026-09-18) and a single `LANG`
line that makes the tool speak them. Generated by tools/make_notebook.py so the four narrations cannot drift."""
import json

from bioms_zaku.datasets import copy_examples, examples_dir

NB = "zaku_exemplo.ipynb"


def _nb() -> dict:
    return json.loads((examples_dir() / NB).read_text(encoding="utf-8"))


def test_notebook_ships_with_the_package_and_is_a_valid_notebook():
    nb = _nb()
    assert nb["nbformat"] == 4 and nb["cells"], "the notebook must ship inside the package (bioms_zaku/examples)"


def test_first_code_cell_installs_the_package_the_standard_way():
    first = next(c for c in _nb()["cells"] if c["cell_type"] == "code")
    assert "pip install" in "".join(first["source"]) and "bioms-zaku" in "".join(first["source"])


def test_the_data_come_from_the_package_never_from_a_download():
    src = "\n".join("".join(c["source"]) for c in _nb()["cells"] if c["cell_type"] == "code")
    assert "load_example" in src and "example_path" in src
    for forbidden in ("wget", "curl", "urlretrieve", "read_csv('http", 'read_csv("http', "files.upload"):
        assert forbidden not in src, f"the notebook must not need {forbidden}: the data ship with the package"


def test_ships_no_stored_outputs():
    for c in _nb()["cells"]:
        assert not c.get("outputs"), "the notebook ships clean: the reader runs it and sees their own numbers"


def test_copy_examples_hands_over_data_and_notebook_together(tmp_path):
    folder = copy_examples(tmp_path / "exemplos")
    names = {p.name for p in folder.iterdir()}
    assert {"zaku_exemplo.csv", NB} <= names


def test_narration_is_in_the_four_languages_with_no_language_left_behind():
    src = "\n".join("".join(c["source"]) for c in _nb()["cells"] if c["cell_type"] == "markdown")
    counts = {tag: src.count(f"**{tag}** —") for tag in ("EN", "ES", "PT", "IT")}
    assert min(counts.values()) >= 6, f"too little narration per language: {counts}"
    assert len(set(counts.values())) == 1, f"the four narrations must have the same number of blocks: {counts}"


def test_one_line_switches_the_language_of_the_tool():
    src = "\n".join("".join(c["source"]) for c in _nb()["cells"] if c["cell_type"] == "code")
    assert 'LANG = "en"' in src and "set_language(LANG)" in src
    assert all(l in src for l in ("en", "es", "pt", "it"))


def test_the_public_api_is_used_as_a_reader_would_write_it():
    src = "\n".join("".join(c["source"]) for c in _nb()["cells"] if c["cell_type"] == "code")
    assert "from bioms_zaku.api import check, example_path, run" in src, "the notebook must use the package surface"


def test_the_logo_opens_the_notebook_and_is_embedded():
    """EN: the logo travels inside the notebook (base64), never as a link: a notebook opened offline, or from a
    private repository, must still show it (user request, 2026-09-18). The small logo is used on purpose."""
    nb = _nb()
    first = "".join(nb["cells"][0]["source"])
    assert nb["cells"][0]["cell_type"] == "markdown"
    assert "data:image/png;base64," in first, "the notebook must open with the embedded logo"
    head = first.split("# BioMS")[0]
    assert "http" not in head, "the logo must not be fetched from the network"
