"""EN: the example notebook ships with the package and runs from a plain `pip install`: the data come from inside the
package (no download, no path to fix), and `examples --copy` hands it over together with the CSV. ONE notebook, with
the narration in ENGLISH ONLY (user decision, 2026-09-24, replacing the four-language narration of 2026-09-18) and a
single `LANG` line that makes the TOOL speak English, Spanish, Portuguese or Italian. The rule is the documentation's
since 2026-09-21: what you read ABOUT the tool is English, what the tool SAYS to you is in your language. Generated by
tools/make_notebook.py so the notebook always ships without outputs."""
import json

from bioms_zaku.datasets import copy_examples, examples_dir

NB = "zaku_exemplo.ipynb"


def _nb() -> dict:
    return json.loads((examples_dir() / NB).read_text(encoding="utf-8"))


def test_notebook_ships_with_the_package_and_is_a_valid_notebook():
    nb = _nb()
    assert nb["nbformat"] == 4 and nb["cells"], "the notebook must ship inside the package (bioms_zaku/examples)"


def test_first_code_cell_installs_the_package_the_standard_way():
    first = next(c for c in _nb()["cells"] if c["cell_type"] == "code")
    assert "pip install" in "".join(first["source"]) and "bioms-zaku" in "".join(first["source"])


def test_the_data_come_from_the_package_never_from_a_download():
    src = "\n".join("".join(c["source"]) for c in _nb()["cells"] if c["cell_type"] == "code")
    assert "load_example" in src and "example_path" in src
    for forbidden in ("wget", "curl", "urlretrieve", "read_csv('http", 'read_csv("http', "files.upload"):
        assert forbidden not in src, f"the notebook must not need {forbidden}: the data ship with the package"


def test_ships_no_stored_outputs():
    for c in _nb()["cells"]:
        assert not c.get("outputs"), "the notebook ships clean: the reader runs it and sees their own numbers"


def test_copy_examples_hands_over_data_and_notebook_together(tmp_path):
    folder = copy_examples(tmp_path / "exemplos")
    names = {p.name for p in folder.iterdir()}
    assert {"zaku_exemplo.csv", NB} <= names


def test_narration_is_english_only():
    """EN: decision of 2026-09-24. Four narrations stacked in every text cell meant a reader scrolled past three
    languages to reach their own, in a notebook whose job is to be understood on a first read. What is NOT removed is
    the tool's four languages: `LANG` still makes messages, figures and the report speak them (next test)."""
    src = "\n".join("".join(c["source"]) for c in _nb()["cells"] if c["cell_type"] == "markdown")
    for tag in ("ES", "PT", "IT"):
        assert f"**{tag}** —" not in src, f"the narration is English only; found a {tag} block"


def test_every_code_cell_is_explained_before_it_runs():
    """EN: the defect this notebook was rewritten for — a reader could execute it and not edit it. No code cell may
    arrive without a text cell before it saying what it does."""
    kinds = [c["cell_type"] for c in _nb()["cells"]]
    assert kinds[0] == "markdown"
    for i, k in enumerate(kinds[1:], start=1):
        if k == "code":
            assert "markdown" in kinds[:i], f"code cell {i} has no narration before it"


def test_the_reader_is_told_where_to_change_things():
    """EN: the keys a reader must find to point the notebook at their own data, each named in the narration."""
    src = "\n".join("".join(c["source"]) for c in _nb()["cells"] if c["cell_type"] == "markdown")
    for key in ("data.path", "targets", "controls", "strata", "covariates", "preset", "design", "expr"):
        assert key in src, f"the narration never tells the reader about `{key}`"


def test_one_line_switches_the_language_of_the_tool():
    src = "\n".join("".join(c["source"]) for c in _nb()["cells"] if c["cell_type"] == "code")
    assert 'LANG = "en"' in src and "set_language(LANG)" in src
    assert all(l in src for l in ("en", "es", "pt", "it"))


def test_the_chosen_language_reaches_the_run():
    """EN: defect found by the user on 2026-09-24. He set LANG = "pt" and the report came out in English: the notebook
    called `set_language(LANG)` and then handed `run` a configuration WITHOUT a `language` key, so the run fell back to
    the default and discarded the choice without a word. §3.4 puts the choice in one place — the configuration — so the
    notebook has to carry it there. Asserted on the source, because the notebook ships unexecuted."""
    src = "\n".join("".join(c["source"]) for c in _nb()["cells"] if c["cell_type"] == "code")
    assert '"language": LANG' in src, "the configuration must carry LANG, or the run answers in English"
    i_lang, i_cfg = src.index('LANG = '), src.index('"language": LANG')
    assert i_lang < i_cfg, "LANG must be defined before the configuration that uses it"


def test_the_public_api_is_used_as_a_reader_would_write_it():
    src = "\n".join("".join(c["source"]) for c in _nb()["cells"] if c["cell_type"] == "code")
    assert "from bioms_zaku.api import check, example_path, run" in src, "the notebook must use the package surface"


def test_the_logo_opens_the_notebook_and_is_embedded():
    """EN: the logo travels inside the notebook (base64), never as a link: a notebook opened offline, or from a
    private repository, must still show it (user request, 2026-09-18). The small logo is used on purpose."""
    nb = _nb()
    first = "".join(nb["cells"][0]["source"])
    assert nb["cells"][0]["cell_type"] == "markdown"
    assert "data:image/png;base64," in first, "the notebook must open with the embedded logo"
    head = first.split("# BioMS")[0]
    assert "http" not in head, "the logo must not be fetched from the network"
