"""
EN: `bioms-zaku init` — build a configuration from a CSV, interactively or from explicit flags. Suggests, never decides:
    every column assignment is confirmed by the user (or given explicitly with --map). Writes a commented YAML.
ES: `init` — construye la configuración desde un CSV; sugiere, nunca decide.
PT: `init` — constrói a configuração a partir de um CSV; sugere, nunca decide.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Callable

import pandas as pd
import yaml

from .io import SEP_DECIMAL_TRIALS, InputError

# EN: name patterns used only to SUGGEST a column for each role (case-insensitive). ES/PT: padrões só para sugerir.
SUGGEST = {
    "R": r"^(r|res|resist|resistance|resistencia|resistência)(_?ohm|50|_50)?$|resist",
    "Xc": r"^(xc|react|reactance|reatancia|reatância|reactancia)(_?ohm|50|_50)?$|react",
    "H": r"^(h|ht|height|estatura|altura|talla|stature)(_?cm|_?m)?$|height|estatura|altura|talla",
    "W": r"^(w|wt|weight|peso|massa|mass|masa)(_?kg)?$|weight|peso|massa",
    "strata": r"^(sex|sexo|gender|genero|género)$",
    "id": r"^(id|seqn|subject|participant|paciente|patient)$",
}


def detect(path: Path, encoding: str = "utf-8") -> tuple[pd.DataFrame, str, str]:
    """EN: same fixed-order detection as the input contract (§1.2), on all columns. ES/PT: mesma detecção do contrato."""
    text = path.read_text(encoding=encoding).lstrip("﻿")
    valid = []
    for s, d in SEP_DECIMAL_TRIALS:
        try:
            df = pd.read_csv(pd.io.common.StringIO(text), sep=s, decimal=d, engine="python")
        except Exception:
            continue
        if len(df.columns) >= 2:
            num = sum(pd.api.types.is_numeric_dtype(df[c]) for c in df.columns)
            valid.append((num, s, d, df))
    if not valid:
        raise InputError("could not parse the file with any (sep, decimal) pair")
    valid.sort(key=lambda t: -t[0])
    if len(valid) > 1 and valid[0][0] == valid[1][0]:
        raise InputError(f"ambiguous separator/decimal ({[(v[1], v[2]) for v in valid[:2]]}); pass --sep and --decimal")
    num, s, d, df = valid[0]
    return df, s, d


def suggest(columns: list[str]) -> dict[str, str | None]:
    out: dict[str, str | None] = {}
    for role, pat in SUGGEST.items():
        hits = [c for c in columns if re.search(pat, str(c).strip().lower())]
        out[role] = hits[0] if len(hits) == 1 else None      # EN: suggest only when unambiguous
    return out


def build_config(csv: Path, mapping: dict[str, str], *, units: dict[str, str], targets: dict[str, str], controls: dict[str, str],
                 covariates: list[str], strata: str | None, id_col: str | None, sep: str, decimal: str, run_name: str,
                 preset: str = "article", independent: bool = False) -> dict:
    cfg = {
        "run_name": run_name,
        "data": {"path": str(csv), "sep": sep, "decimal": decimal,
                 "columns": {"variables": {k: mapping[k] for k in ("R", "Xc", "H", "W") if k in mapping},
                             "units": units, "targets": targets, "controls": controls, "covariates": covariates,
                             "groups": {}, "id": id_col}},
        "strata": strata,
        "catalog": {"include": ["Lukaski1985_II", "Baumgartner1988_PhA", "Piccoli1994_RH", "Piccoli1994_XcH", "LMI"]},
        "declarations": {"targets_independent_of_variables": bool(independent)},
        "preset": preset,
        "output": {"dir": "./zaku_out", "figures": True},
    }
    if strata:
        cfg["data"]["columns"]["groups"] = {"sexo": strata} if strata else {}
    return cfg


HEADER = """# BioMS Zaku configuration — generated by `bioms-zaku init`. Edit freely; run `bioms-zaku check` before `run`.
# EN: `declarations.targets_independent_of_variables` must be true only if NO target/control is computed from the mapped variables.
# ES: debe ser true solo si NINGÚN objetivo/control se calcula a partir de las variables mapeadas.
# PT: deve ser true só se NENHUM alvo/controle é calculado a partir das variáveis mapeadas.
"""


def init(csv: str, out: str | None = None, *, ask: Callable[[str, str | None], str] | None = None, map_flags: dict[str, str] | None = None,
         sep: str = "auto", decimal: str = "auto", encoding: str = "utf-8", printer: Callable[[str], None] = print) -> Path:
    """
    EN: interactive when `ask` is given; otherwise fully specified by `map_flags` (R, Xc, H, W, H_unit, W_unit, target, control,
        covariates (comma list), strata, id, independent (yes/no)). Never guesses silently.
    ES/PT: interativo com `ask`; senão, totalmente especificado por `map_flags`. Nunca adivinha em silêncio.
    """
    p = Path(csv)
    if sep != "auto" and decimal != "auto":
        df = pd.read_csv(p, sep=sep, decimal=decimal, encoding=encoding); s, d = sep, decimal
    else:
        df, s, d = detect(p, encoding)
    cols = [str(c).strip() for c in df.columns]
    numeric = [c for c, raw in zip(cols, df.columns) if pd.api.types.is_numeric_dtype(df[raw])]
    printer(f"file: {p.name} · {len(df)} rows · {len(cols)} columns · sep={s!r} decimal={d!r}")
    printer("numeric columns: " + ", ".join(numeric))
    sug = suggest(cols)
    flags = dict(map_flags or {})

    def get(role: str, prompt: str, default: str | None, required: bool = True) -> str | None:
        if role in flags:
            v = flags[role]
        elif ask is not None:
            v = ask(prompt + (f" [{default}]" if default else ""), default)
        else:
            v = default
        v = (v or "").strip() or (default or "")
        if required and not v:
            raise InputError(f"{role}: a value is required")
        return v or None

    def col(role: str, prompt: str, required: bool = True) -> str | None:
        v = get(role, prompt, sug.get(role), required)
        if v and v not in cols:
            raise InputError(f"{role}: column {v!r} not in file (columns: {cols})")
        return v

    mapping = {r: col(r, f"column for {r}") for r in ("R", "Xc", "H", "W")}
    units = {"H": get("H_unit", "unit of H (cm|m)", "cm"), "W": get("W_unit", "unit of W (kg|g)", "kg")}
    if units["H"] not in ("cm", "m") or units["W"] not in ("kg", "g"):
        raise InputError("units must be H: cm|m and W: kg|g")
    t = col("target", "target column (what the index should predict)"); c = col("control", "negative-control column (what it should NOT predict)")
    cov = get("covariates", "covariate columns for the utility test, comma-separated (empty = skip)", f"{mapping['W']},{mapping['H']}", required=False)
    covariates = [x.strip() for x in (cov or "").split(",") if x.strip()]
    for x in covariates:
        if x not in cols:
            raise InputError(f"covariate {x!r} not in file")
    strata = col("strata", "stratum column, e.g. sex (empty = none)", required=False)
    id_col = col("id", "identifier column (empty = none)", required=False)
    indep = (get("independent", "Are ALL targets/controls measured independently of R, Xc, H, W (yes/no)?", "no") or "no").lower() in ("yes", "y", "sim", "sí", "si", "true")
    tname = re.sub(r"\W+", "_", t).upper(); cname = re.sub(r"\W+", "_", c).upper()
    cfg = build_config(p, mapping, units=units, targets={tname: t}, controls={cname: c}, covariates=covariates, strata=strata, id_col=id_col,
                       sep=s, decimal=d, run_name=p.stem, independent=indep)
    outp = Path(out) if out else p.with_suffix(".zaku.yaml")
    outp.write_text(HEADER + yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True), encoding="utf-8")
    printer(f"wrote {outp}  → next: bioms-zaku check {outp}")
    return outp
